# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('current_song_uri', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('spotify_uri', models.CharField(max_length=100)),
                ('song_name', models.CharField(max_length=100)),
                ('artists', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=1000)),
                ('vote_count', models.IntegerField()),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareplay_app.Party')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('display_name', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=30, null=True)),
                ('last_login', models.DateField(null=True)),
                ('address', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('current_party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shareplay_app.Party')),
            ],
        ),
        migrations.AddField(
            model_name='party',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareplay_app.User'),
        ),
    ]
