# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareplay_app', '0002_user_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spotify_refresh_token',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
