# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareplay_app', '0003_user_spotify_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='current_song_artists',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='current_song_imageUrl',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='current_song_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='current_song_uri',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
